### ISSUE TITLE
Improper behavior in Chiru Picture Box

### ISSUE THREAD

**Issue by Asttear** [umineko-project/umineko-scripting#23]
**Game language:** All (Chinese/English tested)

**Operating system:** All (Windows tested)

**Episode and chapter where the issue occurs:** Chiru Episodes

**Description of the issue:** In Chiru Picture Box, when using the mouse down wheel to turn to the next page, it jumps to the wrong page and plays the wrong animation. This only happens for the first 5 pages. For example, when I scroll down on page 1, it jumps to page 3 instead of the expected page 2. It behaves the same for the next four pages. However, it is fine when I scroll up to turn back to the previous page, and there is no problem with page 6 and page 7 or using the buttons at the bottom.

**Screenshot of the issue:** 
When on this page, if I scroll down ...
![ZE3KI0% 8)NJGH~ 2I7WPN9](https://user-images.githubusercontent.com/16262778/115268075-72d47c00-a16c-11eb-9a49-08beaef1732d.jpg)
... I got this page ...
![%Z1D%JCK53B6YAFAQ }67LC](https://user-images.githubusercontent.com/16262778/115268223-a0212a00-a16c-11eb-94e8-f6444d8513cf.jpg)
... instead of the page below which is expected.
![K4}0Q9GKY0(AXI%Y3BGV0$7](https://user-images.githubusercontent.com/16262778/115268374-c8a92400-a16c-11eb-91cb-14f47e9b173d.jpg)

**Comment by vit9696** [comment]
Fixed in master, thanks!
