### ISSUE TITLE
Android Textbox Lag Issue

### ISSUE THREAD

**Issue by ardnyx** [umineko-project/umineko-scripting#24]
Game language: Witch-Hunt

Operating system: Android (Huawei Nova 3i)

Episode and chapter where the issue occurs: Since Episode 1

Description of the issue: Since I started the game, when a textbox occurs, the game lags and the text starts getting choppy. I tried changing into different box types but it didn't work. Changing the resolution didn't work either.

Screenshot of the issue: http://imgur.com/a/lb6zL9E

**Comment by vit9696** [comment]
Well, does not look too bad for me. The image shows text during a rather CPU-intensive effect, so I would not be surprised there are lags. Overall Android devices generally have not great GPUs, so we cannot promise you get adequate performance with every device all the time.
