### ISSUE TITLE
"<" Formatting Visible in Ep 1 Ch 6

### ISSUE THREAD

**Issue by ardnyx** [umineko-project/umineko-scripting#25]
Game language: Witch-Hunt

Operating system: Android (Huawei Nova 3i)

Episode and chapter where the issue occurs: Ep 1 Ch 6

I think it might be intentional but it kind of bothers me that this < > is visible (if it is a formatting)

![Screenshot_20210803_194227_org umineko_project onscripter_ru](https://user-images.githubusercontent.com/86859621/128010969-0627ff15-66a5-4a53-bfb8-b84e1cb1b943.jpg)
![Screenshot_20210803_194234_org umineko_project onscripter_ru](https://user-images.githubusercontent.com/86859621/128011005-78c85530-e043-4233-b3c6-8831972ebe00.jpg)
![Screenshot_20210803_194632_org umineko_project onscripter_ru](https://user-images.githubusercontent.com/86859621/128011017-200028e2-a866-44f6-bf4a-29c5132b8f35.jpg)

**Comment by vit9696** [comment]
This is indeed intentional. Non-wh variant uses proper quotes.
