### ISSUE TITLE
About Translating

### ISSUE THREAD

**Issue by Singulariity** [umineko-project/umineko-scripting#31]
Hello. Firstly, this is probably not the right place for my request but I tried everything except Github. Seems like umineko project's mail server is died. I can't reach via mail or even register to forum. Our team started to translate scripts and graphics to Turkish. Currently I am trying to translate files but its really hard because I couldn't find empty graphic files anywhere. My request is these empty graphic files. Does anyone know where can I get them?

You can also see my fork `umineko-scripting-tr`

**Comment by vit9696** [comment]
Hello,

I have just checked our e-mail server, it is working fine, and there should be no issue registering. I suggest you to recheck your e-mail provider. From what I remember, some e-mail servers (e.g. Microsoft) were indeed borked but not on our side.

Please contact me via an e-mail and I will provide a link to the translated files.

Best,
Vit

**Comment by Singulariity** [comment]
Okay, I tried another provider and I registered the forum but I still can't sent a mail. Is it `m@umineko-project.org`? The address on the website is unclear. I tried both 'admin' and 'm' but no use.

**Comment by vit9696** [comment]
Yes, this time you were right, our antispam filters went nuts and started blocking all incoming e-mails. It should be good now.

**Comment by Singulariity** [comment]
Thanks for your help!
