### ISSUE TITLE
Tea Party 1 credits start early

### ISSUE THREAD

**Issue by Jetz72** [umineko-project/umineko-scripting#41]
At the very end of the first Tea Party, the credits roll right after Battler proclaims that he'll erase every last cell of Beatrice's existence. There's usually a bit more dialog and visuals in that conversation, but they now play after the credits. I'm not sure if it was an intentional change so that the start of the credits would line up with the music, but the way the conversation is broken in the middle doesn't seem right.

UmiPro - https://www.youtube.com/watch?v=9eoEMoaw3FQ&t=42m42s
Original - https://www.youtube.com/watch?v=lXKGI_36XkY&t=40m40s

**Comment by vit9696** [comment]
Looks correct to me. Please compare with PS3.

https://youtu.be/GhbiGqQQRBk

**Comment by Jetz72** [comment]
Huh, strange. I didn't think to compare it to the original PS3 version. Leaves me curious if that was a bug introduced when porting it, or an intentional change. It still seems weird to me but I suppose it's legitimate.
