### ISSUE TITLE
Ambiguity

### ISSUE THREAD

**Issue by Monaco-a-Knox** [umineko-project/umineko-scripting#48]
umi6_12.txt

jp:　`殺された６人は、戦人という例外を除けば、女ばかり……。`
up: `Excluding Battler, the six people killed had all been women......`
mg: `The six people killed, excluding Battler, had all been women... `

Should I fix it and make it the same as MangaGamer, or do you prefer to rewrite the sentence?

**Comment by vit9696** [comment]
What is wrong here? Both translations make exactly the same sense to me.

**Comment by Monaco-a-Knox** [comment]
Ambiguity.

`the six people killed had all been women`

I was watching a streamer a few weeks ago and she said "Six women were killed? So seven people died this time?"
MG's translation leaves no room for this kind of interpretation.

It's more a matter of interpretation, so maybe this isn't exactly an mistranslation... Maybe I should ask more people about this to see what they think about it.

**Comment by vit9696** [comment]
I honestly cannot read it this way, but if you have native speakers that also think it is ambiguous, I do not mind changing too much.

**Comment by Monaco-a-Knox** [comment]
I asked a few people and they all agreed it was a confusing, especially if it has no context. They also agree that MG's translation makes much more sense to us. Probably the way we are used to writing influences the way we interpret certain grammatical structures.

Well, if you think the two sentences are exactly the same, you don't have to change. It is your translation, so do what you think is right.

**Comment by vit9696** [comment]
Well, the issue is, neither I am a native speaker, nor I am the author of the English translation. I honestly would like to hear some native speaker opinion on this. Perhaps we can leave the issue open for more people to comment.

**Comment by Monaco-a-Knox** [comment]
Sure! I believe we could ask the guys translating Umineko into Spanish/Italian/Turkish. They are not native, but could give us a different opinion.
By the way, I am not saying that your sentence is wrong, I can understand it, but I can also see how it was misinterpreted.

**Comment by vit9696** [comment]
Yeah, point is:

* if it is ambiguity caused by being not a native speaker, then it is the matter of choice of a better sounding variant (for a native speaker).
* if it is ambiguity caused by genuinely ambiguous phrase, then it is the matter of choice of a less ambiguous variant.

To me the phrase does not sound ambiguous at all, but I also am not a native speaker. Thus we really need one.

**Comment by Singulariity** [comment]
Late reply but I think it's ambiguous too. mg version is more clear.

**Comment by vit9696** [comment]
There is no big difference in either wording, so I just applied the change in master ^_^
