### ISSUE TITLE
Small-caps font detail in witch-hunt

### ISSUE THREAD

**Issue by Singulariity** [umineko-project/umineko-scripting#53]
I wonder why the Witch-Hunt translation didn't use this special small-caps font detail. If this is not intentional, I can add the font styles where they should be without too much effort. I thought about fixing them all, but first I wanted to make sure it wasn't intentional.

**Witch-Hunt:**
![](https://i.imgur.com/W9g8FwR.png)

**UmiPro:**
![](https://i.imgur.com/BVzuDhB.png)

**Comment by vit9696** [comment]
Basically nobody bothered, and also because WH translation is not made by us. Need to be very careful though, because some characters have their names sometimes written in caps and sometimes not.

**Comment by Singulariity** [comment]
I think it is an elegant and beautiful detail. And yes, I know that there are specific exceptions. I will be extra careful about that.
